# Generated by Django 4.2.3 on 2023-07-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(verbose_name='комментарий'),
        ),
    ]
