# Generated by Django 4.2.3 on 2023-07-26 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_mailing_time_mailinglog_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingmessage',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sender.client', verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата последней рассылки'),
        ),
    ]
