# Generated by Django 4.2.3 on 2023-07-27 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sender', '0004_mailingmessage_client_alter_mailinglog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingmessage',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
