# Generated by Django 4.2.3 on 2023-07-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0005_mailingmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='send_status',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='send_time',
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активна'),
        ),
    ]
