# Generated by Django 4.2.3 on 2023-07-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0006_remove_mailing_send_status_remove_mailing_send_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='is_active',
        ),
        migrations.AddField(
            model_name='mailing',
            name='send_status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=9, verbose_name='статус'),
        ),
    ]
