# Generated by Django 4.2.3 on 2023-07-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0009_remove_client_user_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingmessage',
            name='client',
        ),
        migrations.AddField(
            model_name='mailingmessage',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, to='sender.client', verbose_name='клиент'),
        ),
    ]
