# Generated by Django 4.2.3 on 2023-07-30 17:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sender', '0010_remove_mailingmessage_client_mailingmessage_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingmessage',
            options={'verbose_name': 'письмо', 'verbose_name_plural': 'письма'},
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='send_status',
        ),
        migrations.RemoveField(
            model_name='mailingmessage',
            name='mailing',
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активный'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='finish',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='окончание рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sender.mailingmessage', verbose_name='сообщение'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='начало рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('создана', 'создана'), ('завершена', 'завершена'), ('запущена', 'запущена')], default='начало рассылки', max_length=100, verbose_name='статус'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='создана'),
        ),
        migrations.AddField(
            model_name='mailingmessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='send_period',
            field=models.CharField(choices=[('разовая', 'разовая'), ('ежедневно', 'ежедневно'), ('еженедельно', 'еженедельно'), ('ежемесячно', 'ежемесячно')], max_length=150, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='время'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='status',
            field=models.CharField(choices=[('delivered', 'доставлено'), ('not_delivered', 'не доставлено')], max_length=255, verbose_name='статус'),
        ),
    ]
